# Generated by Django 4.1 on 2023-04-21 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='post_image/')),
                ('category', models.CharField(choices=[('Mental health', 'Mental health'), ('Heart disease', 'Heart disease'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], default='Mental health', max_length=32)),
                ('summary', models.TextField(max_length=256)),
                ('content', models.TextField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
